<?php

namespace AppBundle\Repository;

/**
 * PostingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostingRepository extends \Doctrine\ORM\EntityRepository
{
}
